/**
 * Load test of the agency API with correctly signed requests (each with its own nonce).
 *
 *   PB_URL=http://127.0.0.1:3000 PB_API_KEY=... PB_SIGNING_SECRET=... PB_CONNECTION_ID=... \
 *   LOAD_RPS=50 LOAD_SECONDS=30 npx tsx scripts/loadtest.ts
 *
 * Mix: 60% PUT listing (new external_id each time, so every request is a real write + enqueue),
 * 30% GET listing, 10% GET /v1/me. The per-key rate limit (API_RATE_LIMIT_RPS) must allow LOAD_RPS.
 * Fails (exit 1) when p95 exceeds LOAD_P95_MS (default 150) or any request errors.
 */
import { createHash, createHmac, randomBytes } from 'node:crypto';
import autocannon from 'autocannon';

const env = (name: string, fallback?: string): string => {
  const value = process.env[name] ?? fallback;
  if (value === undefined) {
    throw new Error(`${name} is required`);
  }
  return value;
};

const url = env('PB_URL');
const apiKey = env('PB_API_KEY');
const secret = env('PB_SIGNING_SECRET');
const connectionId = env('PB_CONNECTION_ID');
const rps = Number(env('LOAD_RPS', '50'));
const seconds = Number(env('LOAD_SECONDS', '30'));
const p95Budget = Number(env('LOAD_P95_MS', '150'));
const run = randomBytes(3).toString('hex');
let counter = 0;

function signed(method: string, path: string, body = '') {
  const timestamp = String(Math.floor(Date.now() / 1000));
  const nonce = randomBytes(16).toString('hex');
  const canonical = [
    timestamp,
    nonce,
    method,
    path,
    createHash('sha256').update(body).digest('hex'),
  ].join('\n');
  return {
    method,
    path,
    body: body || undefined,
    headers: {
      authorization: `Bearer ${apiKey}`,
      'x-timestamp': timestamp,
      'x-nonce': nonce,
      'x-signature': `v1=${createHmac('sha256', secret).update(canonical).digest('hex')}`,
      ...(body ? { 'content-type': 'application/json' } : {}),
    },
  };
}

const listingBody = (n: number) =>
  JSON.stringify({
    category: 'residential_rent',
    title: `Load test apartment ${n}`,
    description: 'Generated by scripts/loadtest.ts',
    price: 2500 + (n % 1000),
    region: 'central',
    images: [],
    attributes: { type: 'Apartment', bedrooms: 2 },
  });

const instance = autocannon(
  {
    url,
    connections: Math.max(10, Math.ceil(rps / 5)),
    overallRate: rps,
    duration: seconds,
    requests: [
      {
        setupRequest: (req) => {
          const n = counter++;
          const roll = n % 10;
          if (roll < 6) {
            return {
              ...req,
              ...signed(
                'PUT',
                `/v1/connections/${connectionId}/listings/load-${run}-${n}`,
                listingBody(n),
              ),
            };
          }
          if (roll < 9) {
            return {
              ...req,
              ...signed(
                'GET',
                // Ten requests and `roll` steps back is a request with roll 0, i.e. a PUT.
                `/v1/connections/${connectionId}/listings/load-${run}-${Math.max(0, n - 10 - roll)}`,
              ),
            };
          }
          return { ...req, ...signed('GET', '/v1/me') };
        },
      },
    ],
  },
  (error, result) => {
    if (error) {
      console.error(error);
      process.exit(1);
    }
    const statusCounts = Object.entries(result.statusCodeStats ?? {})
      .map(([code, stat]) => `${code}=${(stat as { count: number }).count}`)
      .join(' ');
    // autocannon reports p97.5 rather than p95; p97.5 <= budget implies p95 <= budget.
    const p975 = result.latency.p97_5;
    console.log(
      `requests=${result.requests.total} rps=${result.requests.average} statuses: ${statusCounts}\n` +
        `latency ms: p50=${result.latency.p50} p90=${result.latency.p90} p97.5=${p975} p99=${result.latency.p99} max=${result.latency.max}`,
    );
    // The very first GETs may race their PUT (404): expected. Errors, 5xx and 429 are not.
    const bad = Object.keys(result.statusCodeStats ?? {}).filter(
      (code) => code.startsWith('5') || code === '429',
    );
    if (result.errors > 0 || result.timeouts > 0 || bad.length) {
      console.error(
        `FAIL: errors=${result.errors} timeouts=${result.timeouts} statuses=${bad.join(',')}`,
      );
      process.exit(1);
    }
    if (p975 > p95Budget) {
      console.error(`FAIL: p97.5 ${p975} ms exceeds budget ${p95Budget} ms`);
      process.exit(1);
    }
    console.log(`OK: p97.5 within ${p95Budget} ms`);
  },
);
autocannon.track(instance, { renderProgressBar: false, renderResultsTable: false });
